wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1674566638.455554
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.10.4
      5: 0.13.9
      8:
      - 5
path:
  desc: null
  value: genres_mod.parquet
